### ISSUE TITLE
Release Building

### ISSUE THREAD

**Issue by gbakeman** [nutdotnet/WinNUT-Client#81]
The final step in having full CI/CD is to automate deploying (pre) releases of WinNUT on GitHub. The general structure of the workflow should look like:

- Setup MSBuild
- Checkout code
- Restore packages
- Install Multilingual App Toolkit extension
- Build solution in Release configuration
- Get version from Assembly
- Finalize with automated release action on GitHub

# Tasks

- [x] ~~Complete multilingual automation #58~~ 
  - Not blocking release building
- [x] Full debug building
  - [x] Artifact archive name follows format `winnut-client-debug-[shortSHA]`
  - [x] Verify generated assemblies have correct version following [msbuild format](https://github.com/nutdotnet/WinNUT-Client/wiki/Development#build--release-procedure)
- [ ] Complete new updater and prepare client for production transition to ClickOnce - Depends on #97 
- [ ] Automated releases - Depends on #85 
  - [x] Tags in the format v.major.minor.build trigger a new build in the Release configuration
  - [x] Confirm languages integrated and installer package compiled 
  - [x]  Upload archive of the build output, named `WinNUT-Client-v[version]-noinstall`.
  - [x]  Upload ClickOnce installer published artifacts to their destination
  - [x]  Automatically generate a Release post with a generic message, to be manually added to at a later time.
- [ ] Update documentation
- [ ] Continue manually generating and uploading MSI file. Maintain strict release assets order (MSI goes first) until next full release, then relax order.

**Comment by gbakeman** [comment]
Made a breakthrough with the workflow design 61862cf; we now use a sub action specifically for building, that allows us to keep the same environment throughout a workflow without having to duplicate steps for both Debug and Release builds.
