### ISSUE TITLE
New Setup/Installer Build System Research

### ISSUE THREAD

**Issue by gbakeman** [nutdotnet/WinNUT-Client#85]
# Current situation
WinNUT currently uses the [Visual Studio Install Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects)/[Visual Studio Installer Deployment](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/2kt85ked(v%3dvs.100))/[Visual Studio Setup and Deployment Projects](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ee721500(v=vs.100)#visual-studio-setup-and-deployment-projects) system(s) to build an MSI-based installation package. This system is quite dated (at least as old as Visual Studio 2010), not actively supported by Microsoft and importantly not designed for continuous deployment & integration. The need arises to find a new solution.

# Research
On the [Visual Studio deployment documentation](https://learn.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components?view=vs-2022#create-an-installer-package-windows-desktop), the suggestions for creating a Windows desktop installer package are:
- MSI-based installer using the [WiX Toolset](https://wixtoolset.org/)
- MSI/exe installer packages using the Setup project system _(currently in use)_
- MSI/exe installer packages created using [InstallShield](https://www.revenera.com/install/products/installshield)
- Deploy using [ClickOnce](https://learn.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment?view=vs-2022) deployment system

InstallShield is a proprietary, closed-source and payware solution that does not seem fit for the Nutdotnet/WinNut project. That leaves ClickOnce and WiX which both appear to be decent candidates. WiX and ClickOnce are modern solutions with CI/CD integrations. ClickOnce is already built into Visual Studio and doesn't require additional software to build, so this may be worth looking into first before WiX.

# Tasks
- [x] Define current situation, problems and need
- [x] Preliminary research on available options
- [x] Explore ClickOnce integration with current solution, determine if viable over WiX.
- [ ] Consider building old Setup project by Action again (#81)

**Comment by gbakeman** [comment]
Decided on ClickOnce for now.
